def display_board():
    ligne1 = "*"*17
    colonne = ("*")
    ligne2 = ("-"*3)
    print("welcome to TIC TAC TOE!\nTIC TAC TOE")
    print(ligne1)
    print(colonne,end="")
    a = ("     |")
    print(a,end="")
    b = (f"   |     {colonne}")
    print(b)
    print(colonne,end="")
    print("  ",end="")
    print(f"{ligne2}|{ligne2}|{ligne2}  {colonne}")
    print(colonne,end="")
    c = ("     |")
    print(c,end="")
    d = (f"   |     {colonne}")
    print(d)
    print(colonne,end="")
    print("  ",end="")
    print(f"{ligne2}|{ligne2}|{ligne2}  {colonne}")
    print(colonne,end="")
    e = ("     |")
    print(e,end="")
    f = (f"   |     {colonne}")
    print(f)
    print(ligne1)
    print("\n player X's turn...")
display_board()
def player_input():
    L1 = input("entrer une ligne: ")
    L2 = input("entrer une colonne: ")